name: gameplay
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.2.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  google_fonts: ^2.1.0
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.0
  intl: ^0.17.0
  file_picker: ^4.2.7
  firebase_storage: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  modular_test: ^1.0.1+1
  build_runner: ^2.1.5

flutter:

  uses-material-design: true

  assets:
    - images/

scripts: 
  mobx: flutter pub run build_runner watch